---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# cacc20212040

<!-- badges: start -->
<!-- badges: end -->

The goal of cacc20212040 is to provides geospatial data of Central America to do climate change analysis for 2021 - 2040

## Installation

You can install the development version of cacc20212040 from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("ManuelSpinola/cacc20212040")
```

## Example

This is a basic example which shows you how to use the package:

```{r example, message=FALSE, warning=FALSE}
## basic example code
library(cacc20212040)
library(tidyverse)
library(sf)
library(stars)
```

```{r}
ggplot() +
  geom_stars(data = ca_inm_cm4_8_ssp126_2021_2040[,,,1]) +
  scale_fill_viridis_c(name = "Annual Mean Temperature", option = "C", na.value = "transparent", direction = -1) +
  theme_minimal() +
  coord_equal()
```
